### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Coding-with-Adam** [Coding-with-Adam/response-reporting-dashboard#3]
- [ ] Create more sample data inside reports.csv to reach 100 rows (will be provided by VOST-- @tomahock )
- [ ] Set up online database (SQLite), upload the sample data to it, and connect the database to the app (will be provided by VOST-- @tomahock )
- [ ] Create an application page for people requesting to apply to become vetted users.
- [ ] Create a multi-page app framework, using [Pages](https://dash.plotly.com/urls#dash-pages), that has these pages: homepage, internal, data insights, and application page.
- [ ] Set up [basic authentication](https://github.com/plotly/dash-auth/blob/main/README.md) for [internal.py](https://github.com/Coding-with-Adam/response-reporting-dashboard/blob/main/pages/internal.py) page
- [ ] Make improvements to the app's page so they are ready to be used by VOST Europe:
  - [ ] [homepage](https://github.com/Coding-with-Adam/response-reporting-dashboard/blob/main/pages/homepage.py)
  - [ ] [internal](https://github.com/Coding-with-Adam/response-reporting-dashboard/blob/main/pages/internal.py) page (for tracking flags)
  - [ ] [data insights](https://github.com/Coding-with-Adam/response-reporting-dashboard/blob/main/pages/data-insights.py) page 
  - [ ] [application](https://github.com/Coding-with-Adam/response-reporting-dashboard/blob/main/pages/application.py) page (for people requesting to apply to become vetted users)

**Comment by Coding-with-Adam** [comment]
Hi @tomahock 
Is it possible to prioritize the top two bullet points early next week, so the volunteers can make progress in this project?

**Comment by Coding-with-Adam** [comment]
@JorgeMiguelGomes @tomahock 
would it be possible to achieve this by end of this week? The community members are ready to connect the grid and application data to the database. 

> Set up online database (SQLite), and connect the database to the app

**Comment by JorgeMiguelGomes** [comment]
Hi @Coding-with-Adam,
Maybe the best solution is to create the database in the local environment, so that everyone  can test it?
